# Generated by Django 3.2 on 2022-11-30 14:31

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', '食品'), ('2', '飲料'), ('3', '家電・カメラ'), ('4', 'PC・スマホ・通信'), ('5', '日用雑貨・キッチン用品'), ('6', 'コスメ・健康・医薬品'), ('7', 'インテリア・寝具'), ('8', '服飾・ファッション'), ('9', 'スポーツ'), ('10', '本・電子書籍・音楽'), ('11', 'キッズ・ベビー・玩具'), ('12', 'ゲーム・ホビー・楽器'), ('13', '車・バイク'), ('14', 'ペット・花・DIY'), ('15', 'サービス・リフォーム'), ('16', 'その他')], max_length=3, verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('category', models.ManyToManyField(to='purchase_data.Category', verbose_name='カテゴリー')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='購買日時')),
                ('place', models.CharField(max_length=40, verbose_name='商品受け渡し場所')),
                ('gender', models.CharField(choices=[('1', '女性'), ('2', '男性'), ('3', 'その他・無回答')], max_length=2, verbose_name='性別')),
                ('age', models.CharField(choices=[('1', '〜19歳'), ('2', '20代'), ('3', '30代'), ('4', '40代'), ('5', '50代'), ('6', '60代'), ('7', '70代'), ('8', '80代〜'), ('9', '不明・無回答')], max_length=2, verbose_name='年齢')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='編集日時')),
                ('items', models.ManyToManyField(to='purchase_data.Item')),
            ],
        ),
    ]
