# Generated by Django 3.2 on 2022-12-01 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='購買日時'),
        ),
    ]
