# Generated by Django 3.2.16 on 2022-12-07 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 30, 42, 426586, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(verbose_name='購買日時'),
        ),
    ]
