# Generated by Django 3.2 on 2022-12-08 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0003_auto_20221208_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='item', to='purchase_data.Item', verbose_name='購入商品'),
        ),
        migrations.AlterModelTable(
            name='purchasedata',
            table='purchase_data',
        ),
    ]
