# Generated by Django 3.2 on 2022-12-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0003_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('1', '食品'), ('2', '飲料'), ('3', '家電・カメラ'), ('4', 'PC・スマホ・通信'), ('5', '日用雑貨・キッチン用品'), ('6', 'コスメ・健康・医薬品'), ('7', 'インテリア・寝具'), ('8', '服飾・ファッション'), ('9', 'スポーツ'), ('10', '本・電子書籍・音楽'), ('11', 'キッズ・ベビー・玩具'), ('12', 'ゲーム・ホビー・楽器'), ('13', '車・バイク'), ('14', 'ペット・花・DIY'), ('15', 'サービス・リフォーム'), ('16', 'その他')], default=1, max_length=100, verbose_name='カテゴリー'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
