# Generated by Django 3.2 on 2022-12-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0004_auto_20221208_2152'),
        ('purchase_data', '0004_auto_20221208_2207'),
    ]

    operations = [
    ]
