# Generated by Django 3.2 on 2022-12-09 14:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0005_merge_0004_auto_20221208_2152_0004_auto_20221208_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='purchase_data', to='purchase_data.Item', verbose_name='購入商品'),
        ),
        migrations.CreateModel(
            name='PurchaseDataDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('item', models.ManyToManyField(to='purchase_data.Item', verbose_name='購入商品')),
                ('purchase_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_data.purchasedata')),
            ],
        ),
    ]
