# Generated by Django 3.2 on 2022-12-03 11:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0005_auto_20221202_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 53, 28, 302021, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 11, 53, 28, 301949, tzinfo=utc), verbose_name='購買日時'),
        ),
    ]
