# Generated by Django 3.2 on 2022-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0006_auto_20221209_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedata',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchasedatadetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='purchasedatadetail',
            name='price',
        ),
        migrations.AlterField(
            model_name='purchasedatadetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='数量'),
        ),
    ]
