# Generated by Django 3.2 on 2022-12-03 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0007_auto_20221203_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 13, 0, 20, 775474, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 13, 0, 20, 775393, tzinfo=utc), verbose_name='購買日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='items',
            field=models.ManyToManyField(to='purchase_data.Item', verbose_name='購入商品'),
        ),
    ]
