# Generated by Django 3.2 on 2022-12-10 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0007_auto_20221210_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedatadetail',
            name='item',
        ),
        migrations.AddField(
            model_name='purchasedatadetail',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchase_data.item', verbose_name='購入商品'),
        ),
        migrations.AlterField(
            model_name='purchasedatadetail',
            name='purchase_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase_data.purchasedata'),
        ),
    ]
