# Generated by Django 3.2 on 2022-12-03 19:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0008_auto_20221203_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 19, 57, 50, 977686, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 19, 57, 50, 977605, tzinfo=utc), verbose_name='購買日時'),
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
