# Generated by Django 3.2 on 2022-12-04 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0009_auto_20221204_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 15, 5, 22, 569358, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 15, 5, 22, 569285, tzinfo=utc), verbose_name='購買日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='purchase_data.Item', verbose_name='購入商品'),
        ),
    ]
