# Generated by Django 3.2 on 2022-12-04 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_data', '0010_auto_20221205_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedata',
            old_name='items',
            new_name='item',
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 18, 24, 22, 448744, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 18, 24, 22, 448662, tzinfo=utc), verbose_name='購買日時'),
        ),
    ]
